### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by tpplyler** [chromaui/intro-storybook-react-template#14]
From terry.plyler@optum.com
Using npm install:
npm ERR! code E401
npm ERR! Unable to authenticate, need: NEGOTIATE, NTLM, BASIC realm="UHG"

Using yarn:
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/aria-query/-/aria-query-5.0.0.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\users\\tplyler\\taskbox\\yarn-error.log".
From yarn-error.log:
Yarn version: 
  1.22.19

Node version: 
  16.2.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/aria-query/-/aria-query-5.0.0.tgz: Request failed "401 Unauthorized"
      at ResponseError.ExtendableBuiltin (c:\users\tplyler\%appdata5\Roaming\nvm\v16.2.0\node_modules\yarn\lib\cli.js:696:66)
      at new ResponseError (c:\users\tplyler\%appdata5\Roaming\nvm\v16.2.0\node_modules\yarn\lib\cli.js:802:124)
      at Request.<anonymous> (c:\users\tplyler\%appdata5\Roaming\nvm\v16.2.0\node_modules\yarn\lib\cli.js:66215:16)
      at Request.emit (node:events:365:28)
      at Request.module.exports.Request.onRequestResponse (c:\users\tplyler\%appdata5\Roaming\nvm\v16.2.0\node_modules\yarn\lib\cli.js:141767:10)
      at ClientRequest.emit (node:events:365:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:621:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:127:17)
      at TLSSocket.socketOnData (node:_http_client:487:22)
      at TLSSocket.emit (node:events:365:28)

**Comment by jonniebigodes** [comment]
Can you try again and see if the issue persists? I've just cloned the repo following the instructions mentioned in the tutorial, and it didn't surface. This could be related to cache or network issues.

Let me know your findings.

Looking forward to hearing from you.

Stay safe
