### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by cha0s** [chromaui/intro-storybook-react-template#15]
Trying storybook. What I tried:

Clone:
```
cha0s@home:/tmp$ npx degit chromaui/intro-storybook-react-template taskbox
> cloned chromaui/intro-storybook-react-template#HEAD to taskbox
```

Yarn:

```
cha0s@home:/tmp$ cd taskbox/
cha0s@home:/tmp/taskbox$ yarn
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "@storybook/builder-webpack5 > fork-ts-checker-webpack-plugin@6.5.2" has unmet peer dependency "typescript@>= 2.7".
warning "@storybook/addon-essentials > @storybook/addon-docs > @babel/plugin-transform-react-jsx@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "react-scripts > eslint-config-react-app > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "@storybook/addon-actions > react-inspector@5.1.1" has incorrect peer dependency "react@^16.8.4 || ^17.0.0".
warning " > @storybook/addon-essentials@6.5.7" has unmet peer dependency "@babel/core@^7.9.6".
warning "@storybook/addon-essentials > @storybook/addon-docs > @mdx-js/react@1.6.22" has incorrect peer dependency "react@^16.13.1 || ^17.0.0".
warning "@storybook/addon-interactions > @devtools-ds/object-inspector > @devtools-ds/themes > @design-systems/utils@2.12.0" has unmet peer dependency "@types/react@*".
warning " > @storybook/preset-create-react-app@4.1.2" has unmet peer dependency "@babel/core@*".
warning "@storybook/preset-create-react-app > @storybook/react-docgen-typescript-plugin@1.0.2-canary.6.9d540b91e815f8fc2f8829189deb00553559ff63.0" has unmet peer dependency "typescript@>= 3.x".
warning "@storybook/preset-create-react-app > @storybook/react-docgen-typescript-plugin > react-docgen-typescript@2.2.2" has unmet peer dependency "typescript@>= 4.3.x".
warning " > @storybook/react@6.5.7" has unmet peer dependency "require-from-string@^2.0.2".
warning "@storybook/react > @babel/preset-flow@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > react-element-to-jsx-string@14.3.4" has incorrect peer dependency "react@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
warning "@storybook/react > react-element-to-jsx-string@14.3.4" has incorrect peer dependency "react-dom@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
[4/4] Building fresh packages...
Done in 12.48s.
```

(don't) run storybook:
```
cha0s@home:/tmp/taskbox$ yarn storybook
yarn run v1.22.17
$ start-storybook -p 6006
info @storybook/react v6.5.7
info 
info => Loading presets
WARN   Failed to load preset: "/tmp/taskbox/node_modules/@storybook/builder-webpack5/dist/cjs/presets/preview-preset.js"
ERR! Error: Cannot find module '/tmp/taskbox/node_modules/fork-ts-checker-webpack-plugin/lib/index.js'. Please verify that the package.json has a valid "main" entry
ERR!     at tryPackage (node:internal/modules/cjs/loader:353:19)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/tmp/taskbox/node_modules/@storybook/builder-webpack5/dist/cjs/preview/iframe-webpack.config.js:22:58)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!  Error: Cannot find module '/tmp/taskbox/node_modules/fork-ts-checker-webpack-plugin/lib/index.js'. Please verify that the package.json has a valid "main" entry
ERR!     at tryPackage (node:internal/modules/cjs/loader:353:19)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/tmp/taskbox/node_modules/@storybook/builder-webpack5/dist/cjs/preview/iframe-webpack.config.js:22:58)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   path: '/tmp/taskbox/node_modules/fork-ts-checker-webpack-plugin/package.json',
ERR!   requestPath: 'fork-ts-checker-webpack-plugin'
ERR! }
info => Serving static files from ././public at /
info Addon-docs: using MDX1
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
ERR! Error: Cannot find module '/tmp/taskbox/node_modules/fork-ts-checker-webpack-plugin/lib/index.js'. Please verify that the package.json has a valid "main" entry
ERR!     at tryPackage (node:internal/modules/cjs/loader:353:19)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/tmp/taskbox/node_modules/react-dev-utils/ForkTsCheckerWebpackPlugin.js:10:34)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!  Error: Cannot find module '/tmp/taskbox/node_modules/fork-ts-checker-webpack-plugin/lib/index.js'. Please verify that the package.json has a valid "main" entry
ERR!     at tryPackage (node:internal/modules/cjs/loader:353:19)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/tmp/taskbox/node_modules/react-dev-utils/ForkTsCheckerWebpackPlugin.js:10:34)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   path: '/tmp/taskbox/node_modules/fork-ts-checker-webpack-plugin/package.json',
ERR!   requestPath: 'fork-ts-checker-webpack-plugin'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
✔ Would you like to send crash reports to Storybook? … yes

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jonniebigodes** [comment]
Hi @cha0s, sorry for the inconvenience here in trying to run the template. To help me triage this a bit better, can you do me a favour and run the following command, `npx storybook info` and paste the results here? So that I can get some additional context on your environment and package versions.

**Comment by cha0s** [comment]
Sorry for delay.

I just reproduced the same broken outcome from a fresh install.

`npx storybook info`:
```
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Firefox: 112.0
  npmPackages:
    @storybook/addon-actions: ^6.5.7 => 6.5.7 
    @storybook/addon-essentials: ^6.5.7 => 6.5.7 
    @storybook/addon-interactions: ^6.5.7 => 6.5.7 
    @storybook/addon-links: ^6.5.7 => 6.5.7 
    @storybook/builder-webpack5: ^6.5.7 => 6.5.7 
    @storybook/jest: ^0.0.10 => 0.0.10 
    @storybook/manager-webpack5: ^6.5.7 => 6.5.7 
    @storybook/node-logger: ^6.5.7 => 6.5.7 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.7 => 6.5.7 
    @storybook/testing-library: ^0.0.11 => 0.0.11 
```

**Comment by jonniebigodes** [comment]
@cha0s, thanks for the feedback. Appreciate it 🙏 !As Storybook 7.0 was just released, I've just made some changes to the template, including adding Vite and Storybook 7.0 in #17. In the meantime, I'll leave this issue open for follow-up and see if the issue still persists.
