### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by ilienkors** [chromaui/intro-storybook-react-template#6]
Hi, I tried to follow tutorial but get this error. Steps to represent:

`npx degit chromaui/intro-storybook-react-template taskbox`
`npm i`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0" from @storybook/addon-actions@6.3.0
npm ERR!   node_modules/@storybook/addon-actions
npm ERR!     dev @storybook/addon-actions@"^6.3.0" from the root project
npm ERR!     @storybook/addon-actions@"6.3.0" from @storybook/addon-essentials@6.3.0
npm ERR!     node_modules/@storybook/addon-essentials
npm ERR!       dev @storybook/addon-essentials@"^6.3.0" from the root project
npm ERR!   9 more (@storybook/addon-essentials, @storybook/addon-links, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm ERR! node_modules/@storybook/api/node_modules/@reach/router
npm ERR!   @reach/router@"^1.3.4" from @storybook/api@6.3.0
npm ERR!   node_modules/@storybook/api
npm ERR!     @storybook/api@"6.3.0" from @storybook/addon-actions@6.3.0
npm ERR!     node_modules/@storybook/addon-actions
npm ERR!       dev @storybook/addon-actions@"^6.3.0" from the root project
npm ERR!       1 more (@storybook/addon-essentials)
npm ERR!     17 more (@storybook/addons, @storybook/addon-essentials, ...)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-10-31T09_19_41_238Z-debug.log
```

**Comment by jonniebigodes** [comment]
Hi, @ilienkors thanks for reaching out to us with your issue we really appreciate it. Could you also do me a favor and post what version of node and npm you're using and also the OS so that this issue could be better triaged? 

Let me know and we'll go from there.

**Comment by ilienkors** [comment]
@jonniebigodes
node - v16.13.0
npm - 8.1.0
Linux Mint 20.2 Cinnamon

**Comment by msolli** [comment]
Using Yarn, there is a different (but maybe related?) error:
```
~/c/m $ npx degit chromaui/intro-storybook-react-template taskbox
> cloned chromaui/intro-storybook-react-template#HEAD to taskbox
~/c/m $ cd taskbox/
~/c/m/taskbox $ yarn
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @testing-library/user-event@12.6.2" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-actions > @storybook/api > @reach/router > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > @storybook/addon-essentials@6.3.0" has unmet peer dependency "@babel/core@^7.9.6".
warning " > @storybook/addon-essentials@6.3.0" has unmet peer dependency "babel-loader@^8.0.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@1.2.4" has unmet peer dependency "@storybook/components@^6.3.0-beta.1".
warning "@storybook/addon-essentials > @storybook/addon-measure@1.2.4" has unmet peer dependency "@storybook/core-events@^6.3.0-beta.1".
warning "@storybook/addon-essentials > @storybook/addon-measure@1.2.4" has unmet peer dependency "@storybook/theming@^6.3.0-beta.1".
warning "@storybook/react > @babel/preset-react@7.13.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-client@6.3.0" has unmet peer dependency "webpack@*".
warning " > @storybook/preset-create-react-app@3.1.7" has unmet peer dependency "@babel/core@*".
warning "@storybook/preset-create-react-app > @pmmmwh/react-refresh-webpack-plugin@0.4.3" has unmet peer dependency "react-refresh@>=0.8.3 <0.10.0".
warning "@storybook/preset-create-react-app > @pmmmwh/react-refresh-webpack-plugin@0.4.3" has unmet peer dependency "webpack@>=4.43.0 <6.0.0".
warning "@storybook/preset-create-react-app > react-docgen-typescript-plugin@0.6.3" has unmet peer dependency "typescript@>= 3.x".
warning "@storybook/preset-create-react-app > react-docgen-typescript-plugin > react-docgen-typescript@1.20.5" has unmet peer dependency "typescript@>= 3.x".
warning "@storybook/react > @babel/preset-flow@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/react-docgen-typescript-plugin@1.0.2-canary.3c70e01.0" has unmet peer dependency "typescript@>= 3.x".
warning "@storybook/react > @babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.12.10" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/react-docgen-typescript-plugin > react-docgen-typescript@2.0.0" has unmet peer dependency "typescript@>= 4.3.x".
warning " > @storybook/testing-react@0.0.17" has unmet peer dependency "@storybook/addons@^6 || >=6.0.0-0 || >=6.1.0-0 || >=6.2.0-0 || >=6.3.0-0 ".
warning " > @storybook/testing-react@0.0.17" has unmet peer dependency "@storybook/client-api@^6 || >=6.0.0-0 || >=6.1.0-0 || >=6.2.0-0 || >=6.3.0-0 ".
[4/4] 🔨  Building fresh packages...
✨  Done in 19.12s.
~/c/m/taskbox $ yarn storybook
yarn run v1.22.17
$ start-storybook -p 6006 -s public
info @storybook/react v6.3.0
info
info => Loading presets
info => Serving static files from ./public at /
info => Loading 1 config file in "/Users/martin/c/m/taskbox/.storybook"
info => Loading 9 other files in "/Users/martin/c/m/taskbox/.storybook"
info => Adding stories defined in "/Users/martin/c/m/taskbox/.storybook/main.js"
info => Using prebuilt manager
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /Users/martin/c/m/taskbox/node_modules/postcss-safe-parser/node_modules/postcss/package.json
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
ERR!     at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
ERR!     at resolveExports (node:internal/modules/cjs/loader:482:36)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/Users/martin/c/m/taskbox/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1095:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /Users/martin/c/m/taskbox/node_modules/postcss-safe-parser/node_modules/postcss/package.json
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
ERR!     at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
ERR!     at resolveExports (node:internal/modules/cjs/loader:482:36)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/Users/martin/c/m/taskbox/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1095:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18) {
ERR!   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~/c/m/taskbox $ node --version
v17.0.1
~/c/m/taskbox $ yarn --version
1.22.17
```
This is on MacOS Monterey 12.0.1.

**Comment by jonniebigodes** [comment]
@msolli thanks for the detailed log, i'm going to check this during the upcoming days and see what might be the issue and follow up with you on it.

**Comment by ethan-kaseff** [comment]
I am having a similar problem as the others above.

**Comment by NMC00** [comment]
Hi, I was having the same issue as @msolli but I followed what @ethan-kaseff said about uninstalling and reinstalling the "postcss-safe-parser" only to run into a new error when I run `yarn storybook`

I'm on a windows machine, node version V17.2.0, here is the log:
`PS C:\Users\Nick\Projects\Intro-To-Storybook\taskbox> yarn storybook
yarn run v1.22.17
$ start-storybook -p 6006
info @storybook/react v6.4.0
info
info => Loading presets
info => Serving static files from C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\public at /
info => Loading Webpack configuration from `node_modules\react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack4 setup
10% building 1/4 modules 3 active ...o-Storybook\taskbox\node_modules\webpack-hot-middleware\client.js?reload=true&quiet=false&noInfo=undefined n
ode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\NormalModule.js:503:5    at C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\Nick\Projects\Intro-To-Storybook\taskbox\node_modules\@pmmmwh\react-refresh-webpack-plugin\loader\index.js:96:7 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Any help would be greatly appreciated!

**Comment by robinsonkwame** [comment]
@jonniebigodes any progress? New storybook users can not learn about storybook using the official tutorial until this is resolved. I am experiencing the same issue as @msolli.

**Comment by LingVuDev** [comment]
This is due to the node version 17! Just switch to node version 16. If you have nvm then do `nvm use 16` and it should work.

**Comment by danieldogeanu** [comment]
@LingVuDev I'm on Node version 16 and it doesn't work. Still getting that exact error...

**Comment by danieldogeanu** [comment]
Alright, so I recreated this template from scratch, by installing the latest CRA and initializing the latest Storybook with `npx sb init`. Should I make a Pull Request?

**Comment by jonniebigodes** [comment]
@danieldogeanu and everyone else, sorry for the delayed response on this. But I've been working on some other documentation-related issues that required a bit more time than expected. I've done some testing and it seems that I've solved the issue. The following pull request is up to address this issue (#10 ). 
I've tested it on the following matrix and no issues were found:
- Windows:
  - Node 17.2.0
  - Node 16.13.2
 - Ubuntu:
   - Node 17.2.0
   - Node 16.13.2
 - MacOS Catalina
   - Node 17.2.0
   - Node 16.13.2
 
If you want to test it yourselves, run the following command in your terminal:
```shell
npx degit  chromaui/intro-storybook-react-template#bump_dependencies taskbox
```

Have a great weekend!

Stay safe all

**Comment by danieldogeanu** [comment]
Unfortunately I still get an error on Windows 10, but it might be because I'm on Node 16.8.0 (unfortunately I can't upgrade now). Wouldn't be easier to recreate it from scratch? I did and worked perfectly. I even managed to install the other addons from the tutorial without any problems. This is why I was asking if I can do a PR.

<details>
  <summary>Here's the error I get...</summary>

  ```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-scripts@4.0.1
npm ERR! Found: typescript@4.5.5
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">= 3.x" from react-docgen-typescript-plugin@0.6.3
npm ERR!   node_modules/react-docgen-typescript-plugin
npm ERR!     react-docgen-typescript-plugin@"^0.6.2" from @storybook/preset-create-react-app@3.1.7
npm ERR!     node_modules/@storybook/preset-create-react-app
npm ERR!       dev @storybook/preset-create-react-app@"^3.1.7" from the root project
npm ERR!   peer typescript@">= 3.x" from @storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0
npm ERR!   node_modules/@storybook/react-docgen-typescript-plugin
npm ERR!     @storybook/react-docgen-typescript-plugin@"1.0.2-canary.253f8c1.0" from @storybook/react@6.4.18
npm ERR!     node_modules/@storybook/react
npm ERR!       dev @storybook/react@"^6.4.18" from the root project
npm ERR!       3 more (@storybook/preset-create-react-app, ...)
npm ERR!   2 more (react-docgen-typescript, react-docgen-typescript)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"4.0.1" from the root project
npm ERR!   peer react-scripts@">=3.0.0" from @storybook/preset-create-react-app@3.1.7
npm ERR!   node_modules/@storybook/preset-create-react-app
npm ERR!     dev @storybook/preset-create-react-app@"^3.1.7" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@3.9.10
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"4.0.1" from the root project
npm ERR!     peer react-scripts@">=3.0.0" from @storybook/preset-create-react-app@3.1.7
npm ERR!     node_modules/@storybook/preset-create-react-app
npm ERR!       dev @storybook/preset-create-react-app@"^3.1.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
  ```
</details>

PS: Sorry I bothered you in the weekend! 😕

**Comment by robinsonkwame** [comment]
MacOS Monterey, Node 17.4 `yarn storybook` gives a broken build with 

<details><summary>ERR_PACKAGE_PATH_NOT_EXPORTED</summary>
```
$ yarn storybook
yarn run v1.22.17
$ start-storybook -p 6006
info @storybook/react v6.4.18
info 
info => Loading presets
info => Serving static files from ././public at /
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /.../Research/frontend-playground/taskbox/node_modules/postcss-safe-parser/node_modules/postcss/package.json
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
ERR!     at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
ERR!     at resolveExports (node:internal/modules/cjs/loader:482:36)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/.../Research/frontend-playground/taskbox/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /.../Research/frontend-playground/taskbox/node_modules/postcss-safe-parser/node_modules/postcss/package.json
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
ERR!     at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
ERR!     at resolveExports (node:internal/modules/cjs/loader:482:36)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/.../Research/frontend-playground/taskbox/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18) {
ERR!   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
```
</details>

**Comment by danieldogeanu** [comment]
@jonniebigodes Yeah, no dice! I cleared `npx` and `npm` cache and it's still not working, I get the same error. It has conflicting peer dependencies in `react-script` for `typescript`. And I don't think it's a problem with not using `yarn`.

<details>
  <summary>Here's the error...</summary>

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-scripts@4.0.1
npm ERR! Found: typescript@4.5.5
npm ERR!   node_modules/react-docgen-typescript-plugin
npm ERR!     react-docgen-typescript-plugin@"^0.6.2" from @storybook/preset-create-react-app@3.1.7
npm ERR!     node_modules/@storybook/preset-create-react-app
npm ERR!       dev @storybook/preset-create-react-app@"^3.1.7" from the root project
npm ERR!   peer typescript@">= 3.x" from @storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0
npm ERR!   node_modules/@storybook/react-docgen-typescript-plugin
npm ERR!     @storybook/react-docgen-typescript-plugin@"1.0.2-canary.253f8c1.0" from @storybook/react@6.4.18
npm ERR!     node_modules/@storybook/react
npm ERR!       dev @storybook/react@"^6.4.18" from the root project
npm ERR!       3 more (@storybook/preset-create-react-app, ...)
npm ERR!   2 more (react-docgen-typescript, react-docgen-typescript)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"4.0.1" from the root project
npm ERR!   peer react-scripts@">=3.0.0" from @storybook/preset-create-react-app@3.1.7
npm ERR!   node_modules/@storybook/preset-create-react-app
npm ERR!     dev @storybook/preset-create-react-app@"^3.1.7" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@3.9.10
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"4.0.1" from the root project
npm ERR!     peer react-scripts@">=3.0.0" from @storybook/preset-create-react-app@3.1.7
npm ERR!     node_modules/@storybook/preset-create-react-app
npm ERR!       dev @storybook/preset-create-react-app@"^3.1.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
</details>

As I said, I recreated this repo by installing latest CRA and Storybook, and filled in the differences and assets. It works perfectly.

<details>
<summary>Here's the `package.json` from the recreated version.</summary>

```
{
  "name": "taskbox",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ],
    "overrides": [
      {
        "files": [
          "**/*.stories.*"
        ],
        "rules": {
          "import/no-anonymous-default-export": "off"
        }
      }
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.4.18",
    "@storybook/addon-essentials": "^6.4.18",
    "@storybook/addon-interactions": "^6.4.18",
    "@storybook/addon-links": "^6.4.18",
    "@storybook/builder-webpack5": "^6.4.18",
    "@storybook/jest": "^0.0.6",
    "@storybook/manager-webpack5": "^6.4.18",
    "@storybook/node-logger": "^6.4.18",
    "@storybook/preset-create-react-app": "^4.0.0",
    "@storybook/react": "^6.4.18",
    "@storybook/testing-library": "^0.0.9",
    "@storybook/testing-react": "^1.2.3",
    "webpack": "^5.68.0"
  }
}
```
</details>

I've also attached the full recreated version bellow (I can't share the repo link because it's hosted on GitLab and part of a private group).
[taskbox-storybook.zip](https://github.com/chromaui/intro-storybook-react-template/files/8052982/taskbox-storybook.zip)

**Comment by russellbits** [comment]
> I am having a similar problem as the others above.
> 
> ***EDIT: I just saw an issue with packaged named "postcss-safe-parser", so I used npm to uninstall and install it again and it seemed to work.

Thanks @ethan-kaseff—I had the same problem and the uninstall/install solution worked for me as well!

**Comment by StreakInTheSky** [comment]
if you delete `yarn.lock` (and maybe `node_modules`) it works. I'm on node 17.8. Can do a little more testing. I don't know if that's a good enough fix for you guys but can make a PR with the new lock file.

**Comment by jonniebigodes** [comment]
Closing this for now as part of the updates to Storybook 6.5 as with the latest release there was a massive update to the builders for Storybook. Feel free to ping me if the issue resurfaces and I'll gladly re-open it.
